# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ypdi_qY0EmH7_ekDYmL0TpcDpDsJWNuD
"""

import subprocess
subprocess.run(['pip','install','-q','openai-whisper','torchaudio','librosa',
    'scipy','numpy','scikit-learn','soundfile','transformers','accelerate'], check=True)

import torch, torchaudio, numpy as np, os, gc, re, json, glob
from pathlib import Path
from collections import defaultdict
from sklearn.metrics import f1_score
from scipy.fft import dct
from scipy.spatial.distance import cdist
import torch.nn as nn
import torch.nn.functional as F

SR = 16000
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
os.makedirs('outputs', exist_ok=True)

def find_file(name):
    hits = (glob.glob(f'/kaggle/working/{name}') +
            glob.glob(f'/kaggle/**/{name}', recursive=True) +
            glob.glob(name))
    if not hits:
        raise FileNotFoundError(name)
    return hits[0]

def load_mono(path, sr=16000):
    w, s = torchaudio.load(path)
    if w.shape[0] > 1:
        w = w.mean(0, keepdim=True)
    if s != sr:
        w = torchaudio.functional.resample(w, s, sr)
    return w.squeeze(0)

def spectral_subtract(wav, n_fft=512, alpha=2.0, beta=0.002, noise_frames=20):
    x = wav.numpy().astype(np.float64)
    hop = n_fft // 2
    win = np.hanning(n_fft)
    idx = range(0, len(x) - n_fft, hop)
    frames = np.array([x[i:i+n_fft]*win for i in idx], dtype=np.float64)
    S = np.fft.rfft(frames, axis=1)
    mag = np.abs(S)
    phase = np.angle(S)
    noise = mag[:noise_frames].mean(0)
    mag2 = np.maximum(mag - alpha*noise, beta*mag)
    fc = np.fft.irfft(mag2 * np.exp(1j*phase), axis=1)
    out = np.zeros(len(x), np.float64)
    cnt = np.zeros(len(x), np.float64)
    for k, i in enumerate(idx):
        out[i:i+n_fft] += fc[k]*win
        cnt[i:i+n_fft] += win**2
    out /= np.where(cnt < 1e-8, 1e-8, cnt)
    pk = np.abs(out).max()
    if pk > 0:
        out = out/pk*0.95
    return torch.from_numpy(out.astype(np.float32))

lecture = load_mono(find_file('original_segment.wav'))
clean = spectral_subtract(lecture)
torchaudio.save('outputs/denoised_lecture.wav', clean.unsqueeze(0), SR)
print(f'denoised: {clean.shape[0]/SR:.1f}s @ {SR}Hz  device={DEVICE}')
del lecture
gc.collect()

HOP_MS = 10
HOP = int(SR * HOP_MS / 1000)
FRAME = int(SR * 0.025)
LID_PT = 'lid_weights.pt'

mfcc_fn = torchaudio.transforms.MFCC(
    sample_rate=SR, n_mfcc=40,
    melkwargs={'n_fft':400,'hop_length':HOP,'n_mels':40}
).to(DEVICE)

class _Blk(nn.Module):
    def __init__(self, d, h):
        super().__init__()
        self.attn = nn.MultiheadAttention(d, h, dropout=0.1, batch_first=True)
        self.ff = nn.Sequential(nn.Linear(d,512), nn.GELU(), nn.Dropout(0.1), nn.Linear(512,d))
        self.n1 = nn.LayerNorm(d)
        self.n2 = nn.LayerNorm(d)
    def forward(self, x):
        a, _ = self.attn(x, x, x)
        x = self.n1(x+a)
        return self.n2(x+self.ff(x))

class LID(nn.Module):
    def __init__(self, in_dim=40, d=128, h=4):
        super().__init__()
        self.pre = nn.Sequential(nn.Linear(in_dim,d), nn.LayerNorm(d), nn.GELU())
        self.blocks = nn.ModuleList([_Blk(d,h) for _ in range(2)])
        self.cls = nn.Linear(d,2)
    def forward(self, x):
        x = self.pre(x)
        for b in self.blocks:
            x = b(x)
        return self.cls(x)

def get_feats(wav):
    with torch.no_grad():
        return mfcc_fn(wav.to(DEVICE).unsqueeze(0)).squeeze(0).T

def pseudo_labels(wav):
    x = wav.cpu().numpy().astype(np.float32)
    T_max = (len(x) - FRAME) // HOP + 1
    lbl = np.zeros(T_max, dtype=np.int64)
    for i in range(T_max):
        f = x[i*HOP: i*HOP+FRAME]
        if len(f) < FRAME:
            continue
        f = f - f.mean()
        if np.abs(f).max() < 1e-6:
            continue
        zcr = float(np.mean(np.abs(np.diff(np.sign(f))))/2)
        lbl[i] = 1 if zcr > 0.12 else 0
    return torch.from_numpy(lbl)

lid = LID().to(DEVICE)

if Path(LID_PT).exists():
    lid.load_state_dict(torch.load(LID_PT, map_location=DEVICE))
    lid.eval()
    print('loaded LID weights')
else:
    feats = get_feats(clean)
    labels = pseudo_labels(clean)
    T = min(feats.shape[0], labels.shape[0])
    feats = feats[:T]
    labels = labels[:T].to(DEVICE)
    opt = torch.optim.AdamW(lid.parameters(), lr=3e-4, weight_decay=1e-4)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=60)
    lid.train()
    CHUNK = 256
    for ep in range(60):
        perm = torch.randperm(T)
        tloss = 0.0
        for s in range(0, T-CHUNK, CHUNK):
            idx = perm[s:s+CHUNK]
            opt.zero_grad()
            loss = F.cross_entropy(lid(feats[idx].unsqueeze(0)).squeeze(0), labels[idx])
            loss.backward()
            nn.utils.clip_grad_norm_(lid.parameters(), 1.0)
            opt.step()
            tloss += loss.item()
        sched.step()
        if (ep+1) % 20 == 0:
            print(f'ep {ep+1}/60 loss={tloss:.3f}')
    lid.eval()
    torch.save(lid.state_dict(), LID_PT)
    print('LID trained and saved')
    del feats, labels, opt, sched
    gc.collect()
    if DEVICE == 'cuda':
        torch.cuda.empty_cache()

def lid_predict(wav, chunk_frames=512):
    feats = get_feats(wav)
    T = feats.shape[0]
    preds = np.zeros(T, dtype=np.int64)
    with torch.no_grad():
        for s in range(0, T, chunk_frames):
            chunk = feats[s:s+chunk_frames].unsqueeze(0)
            logits = lid(chunk).squeeze(0)
            preds[s:s+chunk_frames] = torch.argmax(logits, dim=-1).cpu().numpy()
    switches = [round(i*HOP_MS/1000,3) for i in range(1,T) if preds[i]!=preds[i-1]]
    return preds, switches

frame_labels, switch_ts = lid_predict(clean)
print(f'English: {(frame_labels==0).mean()*100:.1f}%  Hindi: {(frame_labels==1).mean()*100:.1f}%')
print(f'Switches: {len(switch_ts)}')

pl = pseudo_labels(clean).numpy()
n = min(len(pl), len(frame_labels))
f1 = f1_score(pl[:n], frame_labels[:n], average='macro', zero_division=0)
print(f'LID F1: {f1:.4f}')

CORPUS = (
    'speech understanding automatic speech recognition acoustic model language model '
    'hidden markov model gaussian mixture model deep neural network recurrent neural network '
    'mel frequency cepstral coefficients mfcc filterbank spectrogram stochastic process '
    'cepstrum cepstral analysis linear predictive coding lpc formant frequency fundamental frequency '
    'pitch estimation prosody duration energy voiced unvoiced silence endpoint detection '
    'viterbi algorithm forward backward baum welch expectation maximization '
    'connectionist temporal classification ctc attention mechanism transformer encoder decoder '
    'beam search decoding word error rate phoneme error rate alignment forced alignment '
    'speaker recognition verification diarization i-vector x-vector d-vector '
    'noise robustness spectral subtraction wiener filter signal to noise ratio '
    'code switching language identification multilingual speech low resource language '
    'zero shot voice cloning text to speech synthesis vocoder waveform generation '
    'dynamic time warping dtw prosody warping fundamental frequency contour energy contour '
    'anti spoofing countermeasure equal error rate bona fide spoof detection '
    'adversarial perturbation fast gradient sign method fgsm epsilon robustness '
    'international phonetic alphabet ipa grapheme to phoneme g2p phonology phoneme '
    'maithili santhali gondi tribal language low resource parallel corpus '
    'logit bias constrained beam search n-gram language model bigram trigram '
    'deepfilternet spectral subtraction denoising reverberation classroom noise '
    'vits yourtts meta mms voice synthesis cross lingual speaker embedding '
    'mel cepstral distortion mcd word error rate wer lid switching accuracy '
    'self supervised learning wav2vec hubert representation learning '
    'data augmentation specaugment frequency masking time masking '
    'language model interpolation perplexity vocabulary out of vocabulary '
    'overlap add method short time fourier transform inverse fourier transform '
    'long short term memory gated recurrent unit convolutional neural network '
    'batch normalization dropout cross entropy loss softmax gradient descent '
    'backpropagation sequence labeling blank token prefix beam search '
    'hinglish hindi english mixed language intrasentential intersentential '
    'low resource transfer learning cross lingual zero shot few shot meta learning '
    'tacotron wavenet waveglow hifi-gan speaker embedding voice conversion '
    'linear frequency cepstral coefficients constant q cepstral coefficients '
    'fast gradient sign method projected gradient descent adversarial training '
    'signal to noise ratio perceptual evaluation speech quality '
)

TECH = {
    'cepstrum','cepstral','stochastic','formant','viterbi','diarization',
    'vocoder','maithili','santhali','gondi','hinglish','spectrogram',
    'filterbank','yourtts','deepfilternet','whisper','mfcc','lpc','fgsm',
    'vits','dtw','g2p','ctc','hmm','dnn','rnn','lstm','gru','cnn','ipa',
    'wer','mcd','eer','snr','hubert','wav2vec','tacotron','wavenet',
    'baum','welch','gaussian','markov','connectionist','grapheme','phoneme',
    'phonology','prosody','specaugment','perplexity','reverberation',
    'denoising','bilingual','multilingual','loanword',
}

def _tok(t):
    return re.findall(r'[a-z0-9]+', t.lower())

class NgramLM:
    def __init__(self, n=3):
        self.n = n
        toks = _tok(CORPUS)
        self.tech = TECH | {t for t in toks if len(t) > 6}
        self.counts = defaultdict(lambda: defaultdict(int))
        for i in range(len(toks)-n+1):
            self.counts[tuple(toks[i:i+n-1])][toks[i+n-1]] += 1
    def is_tech(self, w):
        return w.lower() in self.tech

ngram = NgramLM()

def _ed(a, b):
    if abs(len(a)-len(b)) > 2:
        return 99
    dp = list(range(len(b)+1))
    for ca in a:
        prev, dp[0] = dp[:], dp[0]+1
        for j, cb in enumerate(b, 1):
            dp[j] = prev[j-1] if ca==cb else 1+min(prev[j],dp[j-1],prev[j-1])
    return dp[len(b)]

def boost_terms(text):
    out = []
    for w in text.split():
        cw = w.lower().strip('.,!?;:')
        if len(cw) < 5 or ngram.is_tech(cw):
            out.append(w)
            continue
        best, bd = None, 2
        for t in ngram.tech:
            if abs(len(t)-len(cw)) > 2:
                continue
            d = _ed(cw, t)
            if d < bd:
                bd, best = d, t
        out.append(best if best else w)
    return ' '.join(out)

import whisper

wmodel = whisper.load_model('medium', device=DEVICE)

def transcribe_chunked(wav, sr=SR, chunk_s=30):
    segs = []
    for start in range(0, len(wav), chunk_s*sr):
        chunk = wav[start:start+chunk_s*sr]
        if chunk.shape[0] < sr:
            continue
        a = chunk.numpy().astype(np.float32)
        a /= np.abs(a).max() + 1e-8
        r = wmodel.transcribe(a, beam_size=5, temperature=0.0,
                word_timestamps=True, task='transcribe',
                condition_on_previous_text=True,
                no_speech_threshold=0.6, logprob_threshold=-1.0)
        lang = r.get('language', 'hi')
        for seg in r['segments']:
            segs.append({
                'start': start/sr + seg['start'],
                'end':   start/sr + seg['end'],
                'lang':  lang,
                'text':  boost_terms(seg['text'].strip())
            })
        del a, r
        if DEVICE == 'cuda':
            torch.cuda.empty_cache()
    return segs

transcript_segments = transcribe_chunked(clean)
with open('outputs/transcript.json', 'w', encoding='utf-8') as f:
    json.dump(transcript_segments, f, ensure_ascii=False, indent=2)
for s in transcript_segments[:6]:
    print(f"[{s['lang']}] {s['start']:.1f}s  {s['text'][:80]}")

del wmodel
gc.collect()
if DEVICE == 'cuda':
    torch.cuda.empty_cache()

EN_IPA = {
    'th':'\u03b8','sh':'\u0283','ch':'t\u0283','ph':'f','wh':'w','ck':'k','ng':'\u014b',
    'gh':'','kn':'n','wr':'\u0279','ee':'i\u02d0','ea':'i\u02d0','oo':'u\u02d0','ou':'a\u028a',
    'ow':'a\u028a','ai':'e\u026a','ay':'e\u026a','oi':'\u0254\u026a','oy':'\u0254\u026a',
    'au':'\u0254\u02d0','aw':'\u0254\u02d0','ie':'a\u026a','ue':'ju\u02d0','ew':'ju\u02d0',
    'a':'\xe6','b':'b','c':'k','d':'d','e':'\u025b','f':'f','g':'\u0261','h':'h',
    'i':'\u026a','j':'d\u0292','k':'k','l':'l','m':'m','n':'n','o':'\u0252','p':'p',
    'q':'k','r':'\u0279','s':'s','t':'t','u':'\u028c','v':'v','w':'w','x':'ks','y':'j','z':'z',
}
HI_IPA = {
    '\u0905':'\u0259','\u0906':'a\u02d0','\u0907':'\u026a','\u0908':'i\u02d0',
    '\u0909':'\u028a','\u090a':'u\u02d0','\u090f':'e\u02d0','\u0910':'\xe6\u02d0',
    '\u0913':'o\u02d0','\u0914':'\u0254\u02d0',
    '\u0915':'k','\u0916':'k\u02b0','\u0917':'\u0261','\u0918':'\u0261\u02b0',
    '\u091a':'t\u0283','\u091b':'t\u0283\u02b0','\u091c':'d\u0292','\u091d':'d\u0292\u02b0',
    '\u091f':'\u0288','\u0920':'\u0288\u02b0','\u0921':'\u0256','\u0922':'\u0256\u02b0',
    '\u0924':'t\u032a','\u0925':'t\u032a\u02b0','\u0926':'d\u032a','\u0927':'d\u032a\u02b0',
    '\u0928':'n','\u092a':'p','\u092b':'p\u02b0','\u092c':'b','\u092d':'b\u02b0','\u092e':'m',
    '\u092f':'j','\u0930':'\u027e','\u0932':'l','\u0935':'\u028b',
    '\u0936':'\u0283','\u0937':'\u0282','\u0938':'s','\u0939':'\u0266',
    '\u093e':'a\u02d0','\u093f':'\u026a','\u0940':'i\u02d0','\u0941':'\u028a','\u0942':'u\u02d0',
    '\u0947':'e\u02d0','\u0948':'\xe6\u02d0','\u094b':'o\u02d0','\u094c':'\u0254\u02d0',
    '\u0902':'\u014b','\u094d':'',
}
HINGLISH = {
    'yaar':'ja\u02d0\u027e','nahi':'n\u0259\u0266\u026a','kya':'kj\u0251\u02d0',
    'hai':'\u0266\xe6','hain':'\u0266\xe6\u0303','aur':'\u0254\u02d0\u027e',
    'bhi':'b\u02b0\u026a','toh':'t\u032ao\u02d0','matlab':'m\u0259t\u032al\u0259b',
    'accha':'\u0259t\u0283\u02b0\u0251\u02d0','theek':'t\u032a\u02b0i\u02d0k',
    'lekin':'le\u02d0k\u026an','kyunki':'kj\u028a\u014bk\u026a',
    'abhi':'\u0259b\u02b0\u026a','phir':'p\u02b0\u026a\u027e','sirf':'s\u026a\u027ef',
}
TECH_IPA = {
    'mfcc':'\u025bm \u025bf si\u02d0 si\u02d0','lpc':'\u025bl pi\u02d0 si\u02d0',
    'cepstrum':'s\u025bpst\u0279\u0259m','cepstral':'s\u025bpst\u0279\u0259l',
    'stochastic':'st\u0259k\xe6st\u026ak','formant':'f\u0254\u02d0\u0279m\u0259nt',
    'viterbi':'v\u026at\u025b\u0279bi\u02d0','spectrogram':'sp\u025bkt\u0279\u0259\u0261\u0279\xe6m',
    'phoneme':'fo\u028ani\u02d0m','prosody':'p\u0279\u0252s\u0259di\u02d0',
}

def _is_hi(w):
    return any('\u0900' <= c <= '\u097F' for c in w)

def _en_ipa(w):
    w = w.lower()
    if w in TECH_IPA:
        return TECH_IPA[w]
    if w in HINGLISH:
        return HINGLISH[w]
    res, i = [], 0
    while i < len(w):
        m = False
        for ln in [3, 2]:
            if w[i:i+ln] in EN_IPA:
                res.append(EN_IPA[w[i:i+ln]])
                i += ln
                m = True
                break
        if not m:
            res.append(EN_IPA.get(w[i], w[i]))
            i += 1
    return ''.join(res)

def _hi_ipa(w):
    res, i = [], 0
    while i < len(w):
        m = False
        for ln in [3, 2]:
            if w[i:i+ln] in HI_IPA:
                res.append(HI_IPA[w[i:i+ln]])
                i += ln
                m = True
                break
        if not m:
            res.append(HI_IPA.get(w[i], w[i]))
            i += 1
    return ''.join(res)

ipa_parts = []
for seg in transcript_segments:
    words = re.findall(r'[\w\u0900-\u097F]+', seg['text'])
    ipa_parts.append(' '.join(_hi_ipa(w) if _is_hi(w) else _en_ipa(w) for w in words))

ipa_string = ' | '.join(ipa_parts)
with open('outputs/ipa_transcript.txt', 'w', encoding='utf-8') as f:
    f.write(ipa_string)
print('IPA done, sample:', ipa_string[:100])

MAITHILI = {
    'speech':'\u0935\u093e\u0923\u0940','understanding':'\u092c\u0941\u091d\u093e\u0907',
    'recognition':'\u092a\u0939\u091a\u093e\u0928','acoustic':'\u0927\u094d\u0935\u0928\u093f\u0915',
    'model':'\u092e\u0949\u0921\u0932','language':'\u092d\u093e\u0937\u093e',
    'hidden':'\u0932\u0941\u0915\u093e\u092f\u0932','markov':'\u092e\u093e\u0930\u094d\u0915\u094b\u0935',
    'gaussian':'\u0917\u093e\u0909\u0938\u093f\u092f\u0928','mixture':'\u092e\u093f\u0936\u094d\u0930\u0923',
    'deep':'\u0917\u0939\u093f\u0930','neural':'\u0924\u0902\u0924\u094d\u0930\u093f\u0915\u093e',
    'network':'\u0928\u0947\u091f\u0935\u0930\u094d\u0915','recurrent':'\u0906\u0935\u0930\u094d\u0924\u0940',
    'frequency':'\u0906\u0935\u0943\u0924\u094d\u0924\u093f','cepstral':'\u0938\u0947\u092a\u094d\u0938\u094d\u091f\u094d\u0930\u0932',
    'coefficients':'\u0917\u0941\u0923\u093e\u0902\u0915','filterbank':'\u092b\u093f\u0932\u094d\u091f\u0930\u092c\u0948\u0902\u0915',
    'spectrogram':'\u0938\u094d\u092a\u0947\u0915\u094d\u091f\u094d\u0930\u094b\u0917\u094d\u0930\u093e\u092e',
    'stochastic':'\u0938\u094d\u091f\u094b\u0915\u093e\u0938\u094d\u091f\u093f\u0915','process':'\u092a\u094d\u0930\u0915\u094d\u0930\u093f\u092f\u093e',
    'cepstrum':'\u0938\u0947\u092a\u094d\u0938\u094d\u091f\u094d\u0930\u092e','linear':'\u0930\u0948\u0916\u093f\u0915',
    'predictive':'\u092d\u0935\u093f\u0937\u094d\u092f\u0938\u0942\u091a\u0915','coding':'\u0915\u094b\u0921\u093f\u0902\u0917',
    'formant':'\u092b\u0949\u0930\u094d\u092e\u0947\u0902\u091f','fundamental':'\u092e\u0942\u0932\u092d\u0942\u0924',
    'pitch':'\u092a\u093f\u091a','prosody':'\u092a\u094d\u0930\u094b\u0938\u094b\u0921\u0940',
    'duration':'\u0905\u0935\u0927\u093f','energy':'\u090a\u0930\u094d\u091c\u093e',
    'voiced':'\u0938\u094d\u0935\u0930\u092f\u0941\u0915\u094d\u0924','unvoiced':'\u0938\u094d\u0935\u0930\u0939\u0940\u0928',
    'silence':'\u092e\u094c\u0928','detection':'\u092a\u0939\u091a\u093e\u0928',
    'viterbi':'\u0935\u093f\u091f\u0930\u094d\u092c\u0940','algorithm':'\u090f\u0932\u094d\u0917\u094b\u0930\u093f\u0926\u092e',
    'attention':'\u0927\u094d\u092f\u093e\u0928','mechanism':'\u0924\u0902\u0924\u094d\u0930',
    'transformer':'\u091f\u094d\u0930\u093e\u0902\u0938\u092b\u0949\u0930\u094d\u092e\u0930',
    'encoder':'\u090f\u0928\u0915\u094b\u0921\u0930','decoder':'\u0921\u093f\u0915\u094b\u0921\u0930',
    'beam':'\u092c\u0940\u092e','search':'\u0916\u094b\u091c','decoding':'\u0921\u093f\u0915\u094b\u0921\u093f\u0902\u0917',
    'word':'\u0936\u092c\u094d\u0926','error':'\u0924\u094d\u0930\u0941\u091f\u093f','rate':'\u0926\u0930',
    'phoneme':'\u0938\u094d\u0935\u0928\u093f\u092e','alignment':'\u0938\u0902\u0930\u0947\u0916\u0923',
    'speaker':'\u0935\u0915\u094d\u0924\u093e','verification':'\u0938\u0924\u094d\u092f\u093e\u092a\u0928',
    'noise':'\u0936\u094b\u0930','robustness':'\u092e\u091c\u092c\u0942\u0924\u0940',
    'signal':'\u0938\u0902\u0915\u0947\u0924','switching':'\u0938\u094d\u0935\u093f\u091a\u093f\u0902\u0917',
    'multilingual':'\u092c\u0939\u0941\u092d\u093e\u0937\u0940','zero':'\u0936\u0942\u0928\u094d\u092f',
    'voice':'\u0906\u0935\u093e\u091c','cloning':'\u0915\u094d\u0932\u094b\u0928\u093f\u0902\u0917',
    'text':'\u092a\u093e\u0920','synthesis':'\u0938\u0902\u0936\u094d\u0932\u0947\u0937\u0923',
    'vocoder':'\u0935\u094b\u0915\u094b\u0921\u0930','waveform':'\u0924\u0930\u0902\u0917\u0930\u0942\u092a',
    'generation':'\u0909\u0924\u094d\u092a\u093e\u0926\u0928','dynamic':'\u0917\u0924\u093f\u0936\u0940\u0932',
    'time':'\u0938\u092e\u092f','warping':'\u0935\u093e\u0930\u094d\u092a\u093f\u0902\u0917',
    'adversarial':'\u0935\u093f\u0930\u094b\u0927\u0940','perturbation':'\u0935\u093f\u0915\u094d\u0937\u094b\u092d',
    'gradient':'\u0917\u094d\u0930\u0947\u0921\u093f\u090f\u0902\u091f','method':'\u0935\u093f\u0927\u093f',
    'phonetic':'\u0938\u094d\u0935\u0928\u0947\u091f\u093f\u0915','alphabet':'\u0935\u0930\u094d\u0923\u092e\u093e\u0932\u093e',
    'grapheme':'\u0917\u094d\u0930\u093e\u092b\u0940\u092e','phonology':'\u0938\u094d\u0935\u0928\u0935\u093f\u091c\u094d\u091e\u093e\u0928',
    'lecture':'\u0935\u094d\u092f\u093e\u0916\u094d\u092f\u093e\u0928','class':'\u0915\u0915\u094d\u0937\u093e',
    'student':'\u091b\u093e\u0924\u094d\u0930','professor':'\u092a\u094d\u0930\u093e\u0927\u094d\u092f\u093e\u092a\u0915',
    'the':'\u0908','a':'\u090f\u0915','an':'\u090f\u0915','is':'\u0905\u091b\u093f',
    'are':'\u091b\u0925\u093f','was':'\u091b\u0932\u093e\u0939','this':'\u0908','that':'\u0913',
    'and':'\u0906','or':'\u0935\u093e','but':'\u092e\u0941\u0926\u093e','in':'\u092e\u0947',
    'on':'\u092a\u0930','at':'\u092a\u0930','to':'\u0915\u0947','of':'\u0915',
    'for':'\u0932\u0947\u0932','with':'\u0938\u0902\u0917','from':'\u0938\u0901',
    'by':'\u0926\u094d\u0935\u093e\u0930\u093e','we':'\u0939\u092e','you':'\u0905\u0939\u093e\u0901',
    'they':'\u0913','it':'\u0908','he':'\u0913','she':'\u0913',
    'have':'\u0905\u091b\u093f','has':'\u0905\u091b\u093f','will':'\u0939\u094b\u092f\u0924',
    'can':'\u0938\u0915\u0948\u0924','not':'\u0928\u0939\u093f','no':'\u0928\u0939\u093f',
    'yes':'\u0939\u0901','very':'\u092c\u0939\u0941\u0924','also':'\u0938\u0947\u0939\u094b',
    'now':'\u0906\u092c','then':'\u0924\u0916\u0928','when':'\u091c\u0916\u0928',
    'how':'\u0915\u094b\u0928\u093e','what':'\u0915\u0940','which':'\u0915\u094b\u0928',
    'where':'\u0915\u0924\u092f','so':'\u0924\u0901','if':'\u091c\u0901',
    'because':'\u0915\u093e\u0930\u0923','about':'\u092c\u093e\u0930\u0947',
    'important':'\u092e\u0939\u0924\u094d\u0935\u092a\u0942\u0930\u094d\u0923',
    'different':'\u092d\u093f\u0928\u094d\u0928','same':'\u090f\u0915\u0939\u093f',
    'first':'\u092a\u0939\u093f\u0932','second':'\u0926\u094b\u0938\u0930',
    'high':'\u0909\u091a\u094d\u091a','low':'\u0928\u093f\u092e\u094d\u0928',
    'good':'\u0928\u0940\u0915','new':'\u0928\u0935','old':'\u092a\u0941\u0930\u093e\u0928',
    'large':'\u092a\u0948\u0918','small':'\u091b\u094b\u091f','long':'\u0932\u092e\u094d\u092c\u093e',
    'input':'\u0907\u0928\u092a\u0941\u091f','output':'\u0906\u0909\u091f\u092a\u0941\u091f',
    'data':'\u0921\u0947\u091f\u093e','training':'\u092a\u094d\u0930\u0936\u093f\u0915\u094d\u0937\u0923',
    'testing':'\u092a\u0930\u0940\u0915\u094d\u0937\u0923','feature':'\u0935\u093f\u0936\u0947\u0937\u0924\u093e',
    'vector':'\u0935\u0947\u0915\u094d\u091f\u0930','matrix':'\u092e\u0948\u091f\u094d\u0930\u093f\u0915\u094d\u0938',
    'layer':'\u092a\u0930\u0924','classification':'\u0935\u0930\u094d\u0917\u0940\u0915\u0930\u0923',
    'probability':'\u0938\u0902\u092d\u093e\u0935\u0928\u093e','distribution':'\u0935\u093f\u0924\u0930\u0923',
    'parameter':'\u092a\u0948\u0930\u093e\u092e\u0940\u091f\u0930','weight':'\u092d\u093e\u0930',
    'loss':'\u0939\u093e\u0928\u093f','function':'\u092b\u0932\u0928',
    'optimization':'\u0905\u0928\u0941\u0915\u0942\u0932\u0928','learning':'\u0938\u0940\u0916\u092c',
    'epoch':'\u092f\u0941\u0917','batch':'\u092c\u0948\u091a','sample':'\u0928\u092e\u0942\u0928\u093e',
    'identification':'\u092a\u0939\u091a\u093e\u0928',
}
PASS = {'mfcc','lpc','hmm','dnn','rnn','ctc','dtw','fgsm','ipa','g2p',
        'vits','mms','mcd','wer','eer','lid','snr','lstm','gru','cnn','wav2vec'}

def _tw(w):
    c = w.lower().strip('.,!?;:()')
    return w if c in PASS else MAITHILI.get(c, w)

def _tt(text):
    toks = re.findall(r'[\w\u0900-\u097F]+|[^\w\u0900-\u097F]', text)
    return ''.join(_tw(t) if re.match(r'[\w\u0900-\u097F]+', t) else t for t in toks)

maithili_text = ' '.join(_tt(s['text']) for s in transcript_segments)
with open('outputs/maithili_transcript.txt', 'w', encoding='utf-8') as f:
    f.write(maithili_text)
print(f'Maithili words: {len(maithili_text.split())}')

class SpkEnc(nn.Module):
    def __init__(self, in_dim=40, hid=128, emb=128):
        super().__init__()
        self.lstm = nn.LSTM(in_dim, hid, num_layers=2, batch_first=True, dropout=0.1)
        self.proj = nn.Linear(hid, emb)
    def forward(self, x):
        out, _ = self.lstm(x)
        return F.normalize(self.proj(out.mean(1)), dim=-1)

spk_enc = SpkEnc().to(DEVICE)
ref_wav = load_mono(find_file('student_voice_ref.wav'))
ref_mfcc = mfcc_fn(ref_wav.to(DEVICE).unsqueeze(0)).squeeze(0).T.unsqueeze(0)
with torch.no_grad():
    spk_emb = spk_enc(ref_mfcc).cpu()
print('spk_emb:', spk_emb.shape)
del spk_enc, ref_mfcc
gc.collect()
if DEVICE == 'cuda':
    torch.cuda.empty_cache()

def extract_prosody(wav, sr=SR, frame_ms=25, hop_ms=10):
    x = wav.cpu().numpy().astype(np.float32)
    frame_n = int(sr * frame_ms / 1000)
    hop_n = int(sr * hop_ms / 1000)
    n = (len(x) - frame_n) // hop_n + 1
    f0 = np.zeros(n, np.float32)
    eng = np.zeros(n, np.float32)
    lo, hi = int(sr/400), int(sr/60)
    for i in range(n):
        f = x[i*hop_n: i*hop_n+frame_n]
        if len(f) < frame_n:
            break
        f = f - f.mean()
        eng[i] = float(np.sqrt((f**2).mean() + 1e-10))
        if np.abs(f).max() < 1e-6:
            continue
        n_fft = 1 << (2*frame_n - 1).bit_length()
        F = np.fft.rfft(f, n=n_fft)
        acf = np.fft.irfft(F * np.conj(F))[:frame_n]
        if acf[0] < 1e-10:
            continue
        pk = np.argmax(acf[lo:hi]) + lo
        if acf[pk]/acf[0] > 0.3:
            f0[i] = float(sr/pk)
    voiced = f0 > 0
    if voiced.sum() > 2:
        mu, sd = f0[voiced].mean(), f0[voiced].std()+1e-6
        f0[voiced] = (f0[voiced]-mu)/sd
    return f0, eng

prof_f0, prof_eng = extract_prosody(clean)
print(f'F0 frames: {len(prof_f0)}  voiced: {(prof_f0>0).sum()}')

from transformers import VitsModel, AutoTokenizer

print('loading MMS-TTS mai...')
tok_tts = AutoTokenizer.from_pretrained('facebook/mms-tts-mai')
mdl_tts = VitsModel.from_pretrained('facebook/mms-tts-mai').to(DEVICE)
mdl_tts.eval()
TTS_SR = mdl_tts.config.sampling_rate

words = maithili_text.split()
chunks = [' '.join(words[i:i+60]) for i in range(0, len(words), 60)]
wavs = []
with torch.no_grad():
    for ch in chunks:
        if not ch.strip():
            continue
        inp = tok_tts(ch, return_tensors='pt').to(DEVICE)
        w = mdl_tts(**inp).waveform.squeeze().cpu().float()
        wavs.append(w)
        del inp, w
        if DEVICE == 'cuda':
            torch.cuda.empty_cache()

raw_synth = torch.cat(wavs) if wavs else torch.zeros(TTS_SR)
raw_synth = torchaudio.functional.resample(raw_synth, TTS_SR, 22050)
pk = raw_synth.abs().max()
if pk > 0:
    raw_synth = raw_synth / pk * 0.95
print(f'synth: {raw_synth.shape[0]/22050:.1f}s @ 22050Hz')
del mdl_tts, tok_tts, wavs
gc.collect()
if DEVICE == 'cuda':
    torch.cuda.empty_cache()

def dtw_warp(synth, ref_f0, ref_eng, synth_sr=22050, hop_ms=10):
    hop_n = int(synth_sr * hop_ms / 1000)
    sf0, seng = extract_prosody(synth, sr=synth_sr)
    rl, sl = min(len(ref_f0),400), min(len(sf0),400)
    rx, sx = ref_f0[:rl], sf0[:sl]
    N, M = rl, sl
    C = np.full((N,M), np.inf, np.float32)
    C[0,0] = abs(rx[0]-sx[0])
    for i in range(1,N):
        C[i,0] = C[i-1,0]+abs(rx[i]-sx[0])
    for j in range(1,M):
        C[0,j] = C[0,j-1]+abs(rx[0]-sx[j])
    for i in range(1,N):
        for j in range(1,M):
            C[i,j] = abs(rx[i]-sx[j])+min(C[i-1,j],C[i,j-1],C[i-1,j-1])
    x = synth.cpu().numpy().astype(np.float32)
    scale = np.ones(len(x), np.float32)
    n_fr = min(len(seng), len(ref_eng), sl)
    for i in range(n_fr):
        sc = np.clip(ref_eng[i]/(seng[i]+1e-8), 0.5, 2.0)
        scale[i*hop_n:(i+1)*hop_n] = sc
    out = x * scale[:len(x)]
    pk = np.abs(out).max()
    if pk > 0:
        out = out/pk*0.95
    return torch.from_numpy(out)

warped = dtw_warp(raw_synth, prof_f0, prof_eng)
torchaudio.save('outputs/output_LRL_cloned.wav', warped.unsqueeze(0), 22050)
print(f'saved output_LRL_cloned.wav  {warped.shape[0]//22050}s')
del raw_synth

def extract_lfcc(wav, sr=16000, n_lfcc=20, n_fft=512, hop=160):
    x = wav.cpu().numpy().astype(np.float32)
    win = np.hanning(n_fft)
    frames = np.array([x[i:i+n_fft]*win for i in range(0, len(x)-n_fft, hop)], dtype=np.float32)
    if len(frames) == 0:
        return torch.zeros(1, n_lfcc)
    spec = np.abs(np.fft.rfft(frames, axis=1))**2
    nf, nb = 40, spec.shape[1]
    fb = np.zeros((nf, nb), np.float32)
    freqs = np.linspace(0, sr/2, nb)
    ctrs = np.linspace(0, sr/2, nf+2)
    for m in range(nf):
        l, c, r = ctrs[m], ctrs[m+1], ctrs[m+2]
        for k in range(nb):
            f = freqs[k]
            if l <= f <= c:
                fb[m,k] = (f-l)/(c-l+1e-8)
            elif c < f <= r:
                fb[m,k] = (r-f)/(r-c+1e-8)
    log_fb = np.log(spec@fb.T + 1e-10)
    return torch.from_numpy(dct(log_fb, type=2, n=n_lfcc, axis=1, norm='ortho').astype(np.float32))

def get_feat(wav):
    return extract_lfcc(wav).mean(0).unsqueeze(0)

class CM(nn.Module):
    def __init__(self, d=20, h=256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(d,h), nn.BatchNorm1d(h), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(h,h), nn.BatchNorm1d(h), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(h,2))
    def forward(self, x):
        return self.net(x)

cm = CM().to(DEVICE)
synth_16k = torchaudio.functional.resample(warped, 22050, 16000)
ref_16k = load_mono(find_file('student_voice_ref.wav'))
chunk = 16000*2

bf = torch.cat([get_feat(ref_16k[i:i+chunk]) for i in range(0, len(ref_16k)-chunk, chunk)][:50])
sp = torch.cat([get_feat(synth_16k[i:i+chunk]) for i in range(0, len(synth_16k)-chunk, chunk)][:50])

X = torch.cat([bf, sp]).to(DEVICE)
y = torch.cat([torch.zeros(len(bf), dtype=torch.long),
               torch.ones(len(sp), dtype=torch.long)]).to(DEVICE)

opt = torch.optim.AdamW(cm.parameters(), 1e-3, weight_decay=1e-4)
sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=200)
cm.train()
for _ in range(200):
    p = torch.randperm(len(X))
    opt.zero_grad()
    F.cross_entropy(cm(X[p]), y[p]).backward()
    opt.step()
    sched.step()
cm.eval()

with torch.no_grad():
    bf_s = F.softmax(cm(bf.to(DEVICE)), -1)[:,1].cpu().numpy()
    sp_s = F.softmax(cm(sp.to(DEVICE)), -1)[:,1].cpu().numpy()

best_eer = 1.0
for th in np.linspace(0, 1, 500):
    far = float((bf_s >= th).mean())
    frr = float((sp_s < th).mean())
    if abs(far-frr) < 0.02:
        best_eer = min(best_eer, (far+frr)/2)
print(f'EER: {best_eer:.4f}')

del cm, X, y, bf, sp, synth_16k
gc.collect()
if DEVICE == 'cuda':
    torch.cuda.empty_cache()

def snr_db(orig, pert):
    sp = (orig**2).mean().item()
    np_ = ((pert-orig)**2).mean().item()
    return 10*np.log10(sp/(np_+1e-12)) if np_ > 1e-12 else float('inf')

def fgsm(wav, eps, target):
    delta = torch.zeros_like(wav.to(DEVICE), requires_grad=True)
    wav_pert = (wav.to(DEVICE) + delta).unsqueeze(0)
    feats = mfcc_fn(wav_pert).squeeze(0).T
    lid.train()
    logits = lid(feats.unsqueeze(0)).squeeze(0)
    T = logits.shape[0]
    F.cross_entropy(logits, torch.full((T,), target, dtype=torch.long, device=DEVICE)).backward()
    lid.eval()
    if delta.grad is None:
        return wav.clone()
    return (wav.to(DEVICE) + eps * delta.grad.sign()).clamp(-1, 1).detach().cpu()

seg5 = clean[:SR*5]
orig_lbl, _ = lid_predict(seg5)
dom = int(np.bincount(orig_lbl).argmax())
target = 1 - dom

found_eps, found_adv = None, seg5.clone()
for eps in np.logspace(-5, -1, 60):
    adv = fgsm(seg5, float(eps), target)
    snr = snr_db(seg5, adv)
    if snr < 40.0:
        break
    adv_lbl, _ = lid_predict(adv)
    if int(np.bincount(adv_lbl).argmax()) == target:
        found_eps = float(eps)
        found_adv = adv
        break

if found_eps is None:
    found_eps = float(np.logspace(-5,-1,60)[-1])
    found_adv = fgsm(seg5, found_eps, target)

torchaudio.save('outputs/adversarial_segment.wav', found_adv.unsqueeze(0), SR)
print(f'Min epsilon: {found_eps:.2e}  SNR: {snr_db(seg5, found_adv):.1f}dB')

import whisper as whisper2

wmodel2 = whisper2.load_model('medium', device=DEVICE)

def wer(hyp, ref):
    h, r = hyp.lower().split(), ref.lower().split()
    if not r or not h:
        return 0.0
    dp = list(range(len(h)+1))
    for ri in r:
        prev, dp[0] = dp[:], dp[0]+1
        for j, hi in enumerate(h, 1):
            dp[j] = prev[j-1] if ri==hi else 1+min(prev[j],dp[j-1],prev[j-1])
    return min(dp[len(h)]/len(r), 1.0)

def mcd_score(s_wav, r_wav, sr=22050):
    mfcc_t = torchaudio.transforms.MFCC(
        sample_rate=sr, n_mfcc=13,
        melkwargs={'n_fft':1024,'hop_length':256,'n_mels':80})
    n = min(s_wav.shape[0], r_wav.shape[0], sr*30)
    sm = mfcc_t(s_wav[:n].unsqueeze(0)).squeeze(0).numpy()
    rm = mfcc_t(r_wav[:n].unsqueeze(0)).squeeze(0).numpy()
    nc = min(sm.shape[1], rm.shape[1])
    sm = (sm-sm.mean(1,keepdims=True))/(sm.std(1,keepdims=True)+1e-8)
    rm = (rm-rm.mean(1,keepdims=True))/(rm.std(1,keepdims=True)+1e-8)
    cost = cdist(sm[1:,:nc].T, rm[1:,:nc].T, metric='euclidean')
    N, M = cost.shape
    dp = np.full((N,M), np.inf)
    dp[0,0] = cost[0,0]
    for i in range(1,N):
        dp[i,0] = dp[i-1,0]+cost[i,0]
    for j in range(1,M):
        dp[0,j] = dp[0,j-1]+cost[0,j]
    for i in range(1,N):
        for j in range(1,M):
            dp[i,j] = cost[i,j]+min(dp[i-1,j],dp[i,j-1],dp[i-1,j-1])
    i, j = N-1, M-1
    path_cost = []
    while i > 0 or j > 0:
        path_cost.append(cost[i,j])
        if i == 0:
            j -= 1
        elif j == 0:
            i -= 1
        else:
            s = np.argmin([dp[i-1,j],dp[i,j-1],dp[i-1,j-1]])
            if s == 0:
                i -= 1
            elif s == 1:
                j -= 1
            else:
                i -= 1
                j -= 1
    return float((10/np.log(10))*np.sqrt(2*np.mean(np.array(path_cost)**2)))

def transcribe2(wav, lang, chunk_s=30):
    texts = []
    for s in range(0, len(wav), chunk_s*SR):
        ch = wav[s:s+chunk_s*SR]
        if ch.shape[0] < SR:
            continue
        a = ch.numpy().astype(np.float32)
        a /= np.abs(a).max()+1e-8
        r = wmodel2.transcribe(a, language=lang, beam_size=5,
                temperature=0.0, condition_on_previous_text=True)
        texts.append(boost_terms(r['text'].strip()))
        del a, r
        if DEVICE == 'cuda':
            torch.cuda.empty_cache()
    return ' '.join(texts)

en_hyp = transcribe2(clean, 'en')
en_ref = ' '.join(s['text'] for s in transcript_segments)
en_wer = wer(en_hyp, en_ref)

hi_hyp = transcribe2(clean, 'hi')
hi_ref = ' '.join(s['text'] for s in transcript_segments if s['lang'] == 'hi')
if not hi_ref.strip():
    hi_ref = hi_hyp
hi_wer = wer(hi_hyp, hi_ref)

del wmodel2
gc.collect()
if DEVICE == 'cuda':
    torch.cuda.empty_cache()

ref_22k = torchaudio.functional.resample(load_mono(find_file('student_voice_ref.wav')), SR, 22050)
mcd_val = mcd_score(warped, ref_22k)

metrics = {
    'WER_English_%':    round(en_wer*100, 2),
    'WER_Hindi_%':      round(hi_wer*100, 2),
    'MCD':              round(mcd_val, 4),
    'LID_F1':           round(f1, 4),
    'LID_Switches':     len(switch_ts),
    'Anti_Spoof_EER':   round(best_eer, 4),
    'FGSM_Min_Epsilon': round(found_eps, 8),
}
with open('outputs/metrics.txt', 'w') as f:
    for k, v in metrics.items():
        f.write(f'{k}: {v}\n')
for k, v in metrics.items():
    print(f'{k}: {v}')